[build]
  base = "web/"
  publish = "public/"
  command = "gatsby build && netlify-lambda build src/lambda"
  functions = "./built-lambda"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

# Headers to return with requests for the specified paths
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    # Multi-key header rules are expressed with multi-line strings.
    cache-control = '''
      max-age=31557600,
      no-cache,
      no-store,
      must-revalidate'''

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Redirects
[[redirects]]
  from = "http://voyagerinstruments.netlify.app/*"
  to = "https://voyagerinstruments.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://voyagerinstruments.netlify.com/*"
  to = "https://voyagerinstruments.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://voyagerinstruments.com/*"
  to = "https://voyagerinstruments.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://voyagerinstruments.com/*"
  to = "https://voyagerinstruments.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.voyagerinstruments.com/*"
  to = "https://voyagerinstruments.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.voyagerinstruments.com/*"
  to = "https://voyagerinstruments.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://compasshighschool.org/*"
  to = "https://voyagerinstruments.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://compasshighschool.org/*"
  to = "https://voyagerinstruments.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.compasshighschool.org/*"
  to = "https://voyagerinstruments.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.compasshighschool.org/*"
  to = "https://voyagerinstruments.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/our-team/"
  to = "/staff/"
  status = 301
  force = true
[[redirects]]
  from = "/campus/"
  to = "/tour-our-campus/"
  status = 301
  force = true
[[redirects]]
  from = "/salary-policy/"
  to = "/salary-schedule-and-policies/"
  status = 301
  force = false
[[redirects]]
  from = "/giving/"
  to = "/donate/"
  status = 301
  force = false
[[redirects]]
  from = "/pac/"
  to = "/parent-action-council/"
  status = 301
  force = false
[[redirects]]
  from = "/contribute/"
  to = "/school-fees/"
  status = 301
  force = false
[[redirects]]
  from = "/resources/"
  to = "/research-and-resources/"
  status = 301
  force = false
[[redirects]]
  from = "/volunteer/"
  to = "/get-involved/"
  status = 301
  force = false