
[build]
  base = "web/"
  publish = "public/"
  command = "gatsby build && netlify-lambda build src/lambda"
  functions = "./built-lambda"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true